/* eslint-disable */
// Generated by component library do not modify
import ComponentsNotFoundNotFound from './components/NotFound/NotFound.jsx';
import ComponentsPreviewLoader from './components/preview/Loader.react.js';
import ComponentsPreviewLogo from './components/preview/Logo.js';
import ComponentsCheckboxCheckboxWithLabel from './components/Checkbox/CheckboxWithLabel.jsx';

export default {
  ComponentsNotFoundNotFound: {
    name: 'ComponentsNotFoundNotFound',
    menu: 'Components NotFound NotFound',
    file: './components/NotFound/NotFound.jsx',
    component: ComponentsNotFoundNotFound,
    componentName: 'NotFound',
    description: '',
    customProps: {},
    propsDefinition: {},
    simpleProps: {},
    fullProps: {}
  },
  ComponentsPreviewLoader: {
    name: 'ComponentsPreviewLoader',
    menu: 'Components Preview Loader',
    file: './components/preview/Loader.react.js',
    component: ComponentsPreviewLoader,
    componentName: 'Loader',
    description: '',
    customProps: {},
    propsDefinition: {variant:{type:{name:"enum",value:[{value:"'fluid'",computed:false},{value:"'sections'",computed:false},{value:"'css'",computed:false},{value:"'sectionsCss'",computed:false}]},required:false,description:"",defaultValue:{value:"'fluid'",computed:false}}},
    simpleProps: {variant:"fluid"},
    fullProps: {variant:"fluid"}
  },
  ComponentsPreviewLogo: {
    name: 'ComponentsPreviewLogo',
    menu: 'Components Preview Logo',
    file: './components/preview/Logo.js',
    component: ComponentsPreviewLogo,
    componentName: 'Logo',
    description: '',
    customProps: {},
    propsDefinition: {},
    simpleProps: {},
    fullProps: {}
  },
  ComponentsCheckboxCheckboxWithLabel: {
    name: 'ComponentsCheckboxCheckboxWithLabel',
    menu: 'Components Checkbox CheckboxWithLabel',
    file: './components/Checkbox/CheckboxWithLabel.jsx',
    component: ComponentsCheckboxCheckboxWithLabel,
    componentName: 'CheckboxWithLabel',
    description: '',
    customProps: {},
    propsDefinition: {},
    simpleProps: {},
    fullProps: {}
  },
}
